### ISSUE TITLE
Demo website is failing

### ISSUE THREAD

**Issue by jibe-b** [byurhanbeyzat/gatsby-source-gitlab-example#2]
Hi @byurhanbeyzat, it is cool that someone already wrote a source plugin for Gitlab but the demo website is failing and after having configured the plugin I get `You need to enter an accessToken` even though I configured one and then `  TypeError: Cannot read property 'id' of undefined`.

![Screenshot from 2020-03-26 15-12-27](https://user-images.githubusercontent.com/6146483/77656502-41db4500-6f74-11ea-9137-81de5da9cc72.png)

Do you plan to maintain your plugin? That would be great!

**Comment by byurhanbeyzat** [comment]
@jibe-b Thank you for your notice. I will fix it.

**Comment by byurhanbeyzat** [comment]
@jibe-b 
Sorry for the delay site is up and running. 
The problem was because Gitlab token was expired

I will look to the package when I have time maybe I will update it.
